INFO [SharedPool-Worker-2] 2016-07-25 04:25:35,012  Message.java:532 - Unexpected exception during request; channel = [id: 0x40c292ba, /10.0.0.2:42705 :> /<1ocal node>:9042]
java.io.IOException: Error while read(...): Connection reset by peer
	at io.netty.channel.epoll.Native.readAddress(Native Method) ~[netty - all - 4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:675) ~[netty - all - 4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714) ~[netty - all - 4.0.23.Final.jar:4.0.23.Final]


ERROR [SharedPool-Worker-4] 2016-07-25 04:35:35,123  Message.java:617 - Unexpected exception during request; channel = [id: 0xd30bc260, /10.0.0.2:55526 => /10.0.0.1:9042]
java.lang.RuntimeException: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 0 responses.
	at org.apache.cassandra.auth.CassandraRoleManager.getRole(CassandraRoleManager.java:489) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.auth.CassandraRoleManager.isSuper(CassandraRoleManager.java:293) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.auth.Roles.hasSuperuserStatus(Roles.java:52) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.auth.AuthenticatedUser.isSuper(AuthenticatedUser.java:71) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at com.datastax.bdp.cassandra.auth.DseAuthenticator.checkPermissions(DseAuthenticator.java:382) ~[dse-core-5.0.2.jar:5.0.2]
	at com.datastax.bdp.cassandra.auth.DseAuthenticator.access$300(DseAuthenticator.java:82) ~[dse-core-5.0.2.jar:5.0.2]
	at com.datastax.bdp.cassandra.auth.DseAuthenticator$DseSaslNegotiator.getAuthenticatedUser(DseAuthenticator.java:333) ~[dse-core-5.0.2.jar:5.0.2]
	at org.apache.cassandra.transport.messages.AuthResponse.execute(AuthResponse.java:78) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:513) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:407) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [netty-all-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [netty-all-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:298) [netty-all-4.0.34.Final.jar:4.0.34.Final]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
Caused by: org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 0 responses.
	at org.apache.cassandra.service.ReadCallback.awaitResults(ReadCallback.java:132) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.ReadCallback.get(ReadCallback.java:137) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.AbstractReadExecutor.get(AbstractReadExecutor.java:145) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.StorageProxy$SinglePartitionReadLifecycle.awaitResultsAndRetryOnDigestMismatch(StorageProxy.java:1715) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.StorageProxy.fetchRows(StorageProxy.java:1664) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.StorageProxy.readRegular(StorageProxy.java:1605) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.StorageProxy.read(StorageProxy.java:1524) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.db.SinglePartitionReadCommand$Group.execute(SinglePartitionReadCommand.java:954) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:263) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:224) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.auth.CassandraRoleManager.getRoleFromTable(CassandraRoleManager.java:497) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.auth.CassandraRoleManager.getRole(CassandraRoleManager.java:485) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	... 17 common frames omitted

ERROR [SharedPool-Worker-5] 2016-07-25 04:45:35,234  Message.java:617 - Unexpected exception during request; channel = [id: 0x16977ddb, /10.0.0.2:61415 => /10.0.0.1:9042]
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level LOCAL_ONE
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
	at org.apache.cassandra.auth.RolesCache.getRoles(RolesCache.java:70) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.auth.Roles.hasSuperuserStatus(Roles.java:51) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.auth.AuthenticatedUser.isSuper(AuthenticatedUser.java:71) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at com.datastax.bdp.cassandra.auth.DseAuthenticator.checkPermissions(DseAuthenticator.java:382) ~[dse-core-5.0.2.jar:5.0.2]
	at com.datastax.bdp.cassandra.auth.DseAuthenticator.access$300(DseAuthenticator.java:82) ~[dse-core-5.0.2.jar:5.0.2]
	at com.datastax.bdp.cassandra.auth.DseAuthenticator$DseSaslNegotiator.getAuthenticatedUser(DseAuthenticator.java:333) ~[dse-core-5.0.2.jar:5.0.2]
	at org.apache.cassandra.transport.messages.AuthResponse.execute(AuthResponse.java:78) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:513) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:407) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [netty-all-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [netty-all-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:298) [netty-all-4.0.34.Final.jar:4.0.34.Final]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
Caused by: java.lang.RuntimeException: org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level LOCAL_ONE
	at org.apache.cassandra.auth.CassandraRoleManager.getRole(CassandraRoleManager.java:489) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.auth.CassandraRoleManager.isExistingRole(CassandraRoleManager.java:308) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at com.datastax.bdp.cassandra.auth.DseRoleManager.getRoles(DseRoleManager.java:252) ~[dse-core-5.0.2.jar:5.0.2]
	at org.apache.cassandra.auth.RolesCache$1.load(RolesCache.java:122) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.auth.RolesCache$1.load(RolesCache.java:119) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
	... 20 common frames omitted
Caused by: org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level LOCAL_ONE
	at org.apache.cassandra.db.ConsistencyLevel.assureSufficientLiveNodes(ConsistencyLevel.java:296) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.AbstractReadExecutor.getReadExecutor(AbstractReadExecutor.java:162) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.StorageProxy$SinglePartitionReadLifecycle.<init>(StorageProxy.java:1692) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.StorageProxy.fetchRows(StorageProxy.java:1655) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.StorageProxy.readRegular(StorageProxy.java:1605) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.StorageProxy.read(StorageProxy.java:1524) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.db.SinglePartitionReadCommand$Group.execute(SinglePartitionReadCommand.java:954) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:263) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:224) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.auth.CassandraRoleManager.getRoleFromTable(CassandraRoleManager.java:497) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.auth.CassandraRoleManager.getRole(CassandraRoleManager.java:485) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	... 28 common frames omitted

ERROR [RepairJobTask:4] 2016-07-25 04:55:35,345  CassandraDaemon.java:205 - Exception in thread Thread[RepairJobTask:4,5,RMI Runtime]
java.lang.AssertionError: java.lang.InterruptedException
	at org.apache.cassandra.net.OutboundTcpConnection.enqueue(OutboundTcpConnection.java:172) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.net.MessagingService.sendOneWay(MessagingService.java:771) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.net.MessagingService.sendOneWay(MessagingService.java:739) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.repair.ValidationTask.run(ValidationTask.java:56) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220) ~[na:1.8.0_111]
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335) ~[na:1.8.0_111]
	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339) ~[na:1.8.0_111]
	at org.apache.cassandra.net.OutboundTcpConnection.enqueue(OutboundTcpConnection.java:168) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	... 6 common frames omitted

ERROR [AntiEntropyStage:1] 2016-07-25 05:05:35,456  CassandraDaemon.java:205 - Exception in thread Thread[AntiEntropyStage:1,5,main]
java.lang.AssertionError: null
	at org.apache.cassandra.service.ActiveRepairService$ParentRepairSession.getActiveRepairedSSTableRefsForAntiCompaction(ActiveRepairService.java:546) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.service.ActiveRepairService.doAntiCompaction(ActiveRepairService.java:428) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.repair.RepairMessageVerbHandler.doVerb(RepairMessageVerbHandler.java:145) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:67) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

ERROR [SSTableBatchOpen:2] 2016-07-25 05:15:35,590  DebuggableThreadPoolExecutor.java:227 - Error in ThreadPoolExecutor
java.lang.AssertionError: Data component is missing for sstable/apps/cassandra/data/data2/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-11048
	at org.apache.cassandra.io.sstable.SSTableReader.open(SSTableReader.java:456) ~[cassandra-all-2.1.14.97642.jar:2.1.14.97642]
	at org.apache.cassandra.io.sstable.SSTableReader.open(SSTableReader.java:384) ~[cassandra-all-2.1.14.97642.jar:2.1.14.97642]
	at org.apache.cassandra.io.sstable.SSTableReader$4.run(SSTableReader.java:531) ~[cassandra-all-2.1.14.97642.jar:2.1.14.97642]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Th

WARN  [DbInfoRollup-Scheduler-thread-0] 22016-07-25 05:25:35,901   DbInfoRollupScheduler.java:230 - Error attempting to check lease for periodic update task
org.apache.cassandra.exceptions.ReadTimeoutException: Operation timed out - received only 7 responses.
	at org.apache.cassandra.service.StorageProxy.fetchRows(StorageProxy.java:1491) ~[cassandra-all-2.1.17.1439.jar:2.1.17.1439]
	at org.apache.cassandra.service.StorageProxy.readWithPaxos(StorageProxy.java:1292) ~[cassandra-all-2.1.17.1439.jar:2.1.17.1439]
	at org.apache.cassandra.service.StorageProxy.read(StorageProxy.java:1253) ~[cassandra-all-2.1.17.1439.jar:2.1.17.1439]
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:310) ~[cassandra-all-2.1.17.1439.jar:2.1.17.1439]
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:218) ~[cassandra-all-2.1.17.1439.jar:2.1.17.1439]
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:68) ~[cassandra-all-2.1.17.1439.jar:2.1.17.1439]
	at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:245) ~[cassandra-all-2.1.17.1439.jar:2.1.17.1439]
	at com.datastax.bdp.leases.Lessor.process(Lessor.java:160) ~[dse-core-4.8.12.jar:4.8.12]
	at com.datastax.bdp.leases.Lessor.queryLease(Lessor.java:145) ~[dse-core-4.8.12.jar:4.8.12]
	at com.datastax.bdp.leases.Lessor.tryObtainLease(Lessor.java:65) ~[dse-core-4.8.12.jar:4.8.12]
	at com.datastax.bdp.leases.Lessee.obtainLease(Lessee.java:28) ~[dse-core-4.8.12.jar:4.8.12]
	at com.datastax.bdp.reporting.snapshots.db.DbInfoRollupScheduler$DbInfoRollupTask.isTaskOwner(DbInfoRollupScheduler.java:226) [dse-core-4.8.12.jar:4.8.12]
	at com.datastax.bdp.reporting.snapshots.db.DbInfoRollupScheduler$DbInfoRollupTask.run(DbInfoRollupScheduler.java:128) [dse-core-4.8.12.jar:4.8.12]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_71]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_71]

ERROR [GossipTasks:1] 2017-01-05 15:34:59,614  RepairRunnable.java:261 - Repair session 9fc39482-d353-11e6-9940-7d76bd094de7 for range [(-5041742244861454083,-5031228534686663405], (-5031228534686663405,-5027634690056969021], (-4998749603121144073,-4997554617625990702], (4801964342755268407,4821940070161401515], (-5484640490263850666,-5482659095377290339], (-4992832937061935230,-4983094210752029477], (6080817576420974861,6085344121835895255], (-5631687778475504058,-5628789915215383820], (-8239902477410357537,-8234601316997007237], (-4997554617625990702,-4992832937061935230]] failed with error Endpoint /10.14.150.233 died
java.io.IOException: Endpoint /10.0.0.2 died
	at org.apache.cassandra.repair.RepairSession.convict(RepairSession.java:346) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.gms.FailureDetector.interpret(FailureDetector.java:306) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.gms.Gossiper.doStatusCheck(Gossiper.java:762) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.gms.Gossiper.access$800(Gossiper.java:66) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.gms.Gossiper$GossipTask.run(Gossiper.java:180) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.concurrent.DebuggableScheduledThreadPoolExecutor$UncomplainingRunnable.run(DebuggableScheduledThreadPoolExecutor.java:118) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
ERROR [GossipTasks:1] 2017-01-05 15:34:59,614  RepairSession.java:347 - [repair #9fefd4a1-d353-11e6-9940-7d76bd094de7] session completed with the following error
java.io.IOException: Endpoint /10.0.0.2 died
	at org.apache.cassandra.repair.RepairSession.convict(RepairSession.java:346) ~[cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.gms.FailureDetector.interpret(FailureDetector.java:306) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.gms.Gossiper.doStatusCheck(Gossiper.java:762) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.gms.Gossiper.access$800(Gossiper.java:66) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.gms.Gossiper$GossipTask.run(Gossiper.java:180) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at org.apache.cassandra.concurrent.DebuggableScheduledThreadPoolExecutor$UncomplainingRunnable.run(DebuggableScheduledThreadPoolExecutor.java:118) [cassandra-all-3.0.8.1293.jar:3.0.8.1293]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]